#!/bin/bash

# Bash script to run Aliro Simulator python scripts to generate json files for BBM92 simulations
python aliro_simulator_bbm92/run_sim_dark_count_sweep.py
python aliro_simulator_bbm92/run_sim_dead_time_sweep.py
python aliro_simulator_bbm92/run_sim_detector_jitter_sweep.py
python aliro_simulator_bbm92/run_sim_loss_sweep.py
python aliro_simulator_bbm92/run_sim_source_brightness_sweep.py
python aliro_simulator_bbm92/run_sim_visibility_sweep.py
python aliro_simulator_bbm92/run_sim_coinc_window_sweep.py
